### PR TITLE
New Category: "Tool" with lots of cool android apps.

### PR DESCRIPTION
**Pull request by Uniminin**

### CODE REVIEW

**Comment by Uniminin** [comment]
@TheEvilSkeleton Ping

**Comment by resynth1943** [comment]
I'm on it. Thank you for the wonderful suggestion.

**Comment by resynth1943** [comment]
Do you have any download links to these tools?

**Comment by resynth1943** [comment]
Also, can you please change Tool to Tools? A plural would be gramatically correct here.

**Comment by Uniminin** [comment]
@TheEvilSkeleton Sure.

**Comment by TheEvilSkeleton** [comment]
Where are the source codes?

**Comment by Uniminin** [comment]
@TheEvilSkeleton closed src :)

**Comment by TheEvilSkeleton** [comment]
Sorry, we don't accept proprietary apps.

**Comment by resynth1943** [comment]
Yeah...

**Pull request closed without merging**
